version: '3.7'

services:

  webflux-mongodb:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    volumes:
      - mongo_data1:/data/db
    networks:
      webflux-network:
        aliases:
          - "mongodb"

  webflux-api:
    image: webflux-mongo-demo/api:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - webflux-mongodb
    networks:
      webflux-network:
        aliases:
          - "api"

volumes:
  mongo_data1:
    driver: local

networks:
  webflux-network:
    driver: bridge